name: macOS Tests

on:
  pull_request:
    branches: [ main ]
    
jobs:
  check-changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - '.github/workflows/macos-tests.yml'
              - '**/*.swift'

  build-macos-matrix:
    name: macOS Matrix
    if: ${{ github.event_name == 'push' || needs.check-changes.outputs.changed == 'true' }}
    needs: check-changes
    strategy:
      fail-fast: false
      matrix:
        xcode: [ "16.3", "16.4", "26.0" ]
        os: [ macos-15 ]
    runs-on: ${{ matrix.os }}

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: |
          set -o pipefail && \
          NSUnbufferedIO=YES \
          xcrun xcodebuild test -workspace . -scheme Vexil -skipMacroValidation -destination "platform=macOS,name=My Mac" \
          | xcbeautify --renderer github-actions

  build-macos:
    runs-on: ubuntu-latest
    name: macOS Tests
    if: ${{ needs.check-changes.outputs.changed == 'true' }}
    needs: [ build-macos-matrix, check-changes ]
    steps:
      - name: Check build matrix status
        if: ${{ needs.build-macos-matrix.result != 'success' }}
        run: exit 1
